
defaults: &defaults
  google_maps_key: <YOUR_GOOGLE_API_KEY>
  insertion_filter_url: <FILTER STRING LIKE http://www.finn.no/finn/realestate/lettings/result?PRICE_FROM=10000>

development:
  <<: *defaults

production:
  <<: *defaults
